trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: path/to/your/htmlFile
      artifactName: HtmlReport
